"""create_article_table

Revision ID: f96927a48d66
Revises: 08fbce1e3022
Create Date: 2024-07-28 16:36:42.877716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f96927a48d66"
down_revision: Union[str, None] = "08fbce1e3022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор статьи"),
        sa.Column(
            "user_id", sa.UUID(), nullable=True, comment="Идентификатор пользователя"
        ),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            nullable=True,
            comment="Дата создания статьи",
        ),
        sa.Column(
            "topic_id", sa.UUID(), nullable=True, comment="Идентификатор темы статьи"
        ),
        sa.Column(
            "text", sa.String(length=10000), nullable=True, comment="Текст статьи"
        ),
        sa.Column(
            "views", sa.Integer(), nullable=True, comment="Количество просмотров"
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["article_topic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article")
    # ### end Alembic commands ###
